### PR TITLE
Add sorting to Table on Payroll and Shares pages

### LINKED ISSUE #58: Reorder list of payroll data from newest to oldest

### PR DESCRIPTION
**Pull request by darjanin**
Motivation for this change is that often the interesting information is the newest one and not the one made a 3 years ago. The issue #58 mentions this requirement as well. Table is sorted by first column. It should resolve #58 too.

Changes in the `SharesPage.js` and the `PayrolPage.js` are same. As both pages are using close structure it can be refactor to common PageLayout component in case that we would want to add more pages.

> Options of sorting on tables:
> 
> - no sorting,
> - sorting for specific column without interactivity,
> - sort with interactivy by clicking on the header of table.
> 
> This commit uses the third option.
> 
> There are 3 types of data types supported:
> 
> - date,
> - numbers,
> - string (default).

### CODE REVIEW

**Review by paldys — COMMENTED** [review]
> Changes in the SharesPage.js and the PayrolPage.js are same. As both pages are using close structure it can be refactor to common PageLayout component in case that we would want to add more pages.

Was there something stopping you to create this sorting logic inside the `Table` component? `PayrollPage` and `SharesPage` don't even need to know about how the data is displayed.

At most, there might be something like `initialSortingOptions` for `Table`, but I think that is also unnecessary at the moment, since  both pages start with `{sortByColumnIndex: 0, sortOrder: 'desc'}`.

**Comment by darjanin** [comment]
I worked on it only on Payroll in the start only. After I check the Shares page and saw that filtering and statusbar is duplicated too, I didn't want to move stuff more then needed and just copied the same code into the second page. As the same sorting for both tables was something that I expected that would be fine, but was not sure so rather left it separated.

If the only issue with PR is that it's in separate files I can look at it and move sorting into the Table component. Just need to check if it can break some functionality while you apply filtering.

**Comment by paldys** [comment]
You still didn't convince me. I think this way it's still complicated and that code duplication is really obvious and it tells me that something isn't right.

I can get behind your idea of `TableView`, but I think our `TableView` is already the `Table`. It already knows about data it gets and how to treat it (because it already has the formatting too). Also, sorting the data before passing it to `GridCanvas` would just enforce its visual representation (as it is with the formatting).

Anyway, if you want to refactor it to `TableView` and separate the responsibility, I wouldn't mind if you do it in this PR (in a separate commit). I am quite not okay with the duplicated code though.

**Review by paldys — APPROVED** [review]
It looks much better keeping the sorting logic in one place, thanks. :+1:

**Comment by mlenik** [comment]
Let's rebase and merge...

**Pull request merged**
